plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/BlockLength:
  Enabled: true
  Max: 25
  Exclude:
    - config/environments/development.rb

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/RescueStandardError:
  EnforcedStyle: implicit

Rails/OutputSafety:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: not_to

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
  Max: 25
  CountAsOne:
    - hash
